### PR TITLE
style: Title and input placeholder

### LINKED ISSUE #27: Css Changes and Text Correction
As we can see the text named **Task lists** is not visible due to the similar background. Also the text in the place holder was wrong **What would you link to add**...it should be **What would you like to add**.
before
I have made some minor changes in the text's **Colour** also corrected the **Placeholder's** text...If u liked it i can make a pull request❤️
after

### PR DESCRIPTION
**Pull request by Mouli-3542**
image

Resolves #27

### CODE REVIEW

**Comment by malivinayak** [comment]
PR must be named as style: Title and input placeholder

and in description mention Resolves #27

**Review by malivinayak — CHANGES_REQUESTED** [review]
LGTM

Just update PR Name and description I will merge PR

**Comment by Mouli-3542** [comment]
Sorry its my first time contributing...still learning❤️

**Comment by malivinayak** [comment]
> Sorry its my first time contributing...still learning❤️

As you added `Resolves #'Issue Number'`
The respective issue is automatically added to this PR.
Because of this once this PR is merged respective issue will automatically closed


image

**Review by malivinayak — APPROVED** [review]
Thank You for contribution.

**Comment by Mouli-3542** [comment]
😀❤️Also can u provide ur discord so i could communicate more with you

**Comment by malivinayak** [comment]
can you reopen the same PR again with same msg plz

**Comment by Mouli-3542** [comment]
How do i do that?? idk

**Comment by malivinayak** [comment]
PR Name - `style: Title and input placeholder`
Descriptio - 
```
![image](https://github.com/malivinayak/To-Do-Manager/assets/66154908/4a29f8f8-2bef-4f2f-9350-410bf34be5f1)


Resolves #27
```

**Comment by malivinayak** [comment]
> How do i do that?? idk

Click Here https://github.com/Mouli-3542/To-Do-Manager/tree/main
and there is contribute button, after clicking on contribute you can create PR again

**Comment by malivinayak** [comment]
> How do i do that?? idk

Sorry for trouble i had to force push the revert changes due to wrong commit message

**Comment by Mouli-3542** [comment]
> > How do i do that?? idk
> 
> Sorry for trouble i had to force push the revert changes due to wrong commit message

nvm learned something tho😅

**Comment by malivinayak** [comment]
You can make as much PR as you want in https://github.com/malivinayak/Markdown/

All will counted towards hacktoberfest2023

**Comment by Mouli-3542** [comment]
> You can make as much PR as you want in https://github.com/malivinayak/Markdown/
> 
> All will counted towards hacktoberfest2023

This too will count right??

**Comment by malivinayak** [comment]
> > You can make as much PR as you want in https://github.com/malivinayak/Markdown/
> > All will counted towards hacktoberfest2023
> 
> This too will count right?? 

Yup ✅

**Pull request merged**
